# Generated by Django 3.2.18 on 2023-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайлы'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='6415361_account_avatar_profile_user_icon.png', upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
