# Generated by Django 3.2.18 on 2023-04-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230413_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
